<a href="https://colab.research.google.com/github/MarJuALriv/inteligencia_artificial/blob/master/14Dejulio.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
print(np.__version__)


1.25.2


In [ ]:
# Crear un array de números del 0 al 9
id_array = np.arange(10)

print(id_array)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:


# Crear un vector aleatorio de tamaño 10
vector_aleatorio = np.random.rand(10)

print("Vector aleatorio original:")
print(vector_aleatorio)

# Encontrar el índice del valor máximo
indice_maximo = np.argmax(vector_aleatorio)

# Reemplazar el valor máximo por 0
vector_aleatorio[indice_maximo] = 0

print("Vector después de reemplazar el valor máximo por 0:")
print(vector_aleatorio)


Vector aleatorio original:
[0.56981421 0.27071246 0.3428072  0.04596306 0.40082436 0.79058082
 0.84997687 0.49401276 0.74766453 0.21819197]
Vector después de reemplazar el valor máximo por 0:
[0.56981421 0.27071246 0.3428072  0.04596306 0.40082436 0.79058082
 0.         0.49401276 0.74766453 0.21819197]


In [ ]:
import numpy as np

# Definir el array arr
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

# Encontrar la posición del número 8 usando np.where
indice = np.where(arr == 8)

# Imprimir el número 8 y su posición
print("El número 8 se encuentra en la posición:", indice)
print("El número 8 es:", arr[indice])


El número 8 se encuentra en la posición: (array([1]), array([2]))
El número 8 es: [8]


In [ ]:


# Definir el array arr
arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Obtener los elementos [3, 4, 5] utilizando la indexación
subset = arr[2:5]  # Recordando que el índice en Python comienza en 0

print("Los números [3, 4, 5] del array son:", subset)


Los números [3, 4, 5] del array son: [3 4 5]


In [ ]:
# Definir el array arr
arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Obtener los últimos 4 números utilizando indexación negativa
last_four = arr[-4:]

print("Los últimos 4 números del array son:", last_four)

Los últimos 4 números del array son: [4 5 6 7]


In [ ]:
# Crear una matriz 3x3 de todos True's
true_array = np.ones((3, 3), dtype=bool)

print(true_array)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [ ]:
# Definir el array arr
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Filtrar los números impares usando operaciones de indexación y booleanas
odd_numbers = arr[arr % 2 != 0]

print("Números impares en el array son:", odd_numbers)

Números impares en el array son: [1 3 5 7 9]


In [ ]:
# Crear un vector con valores desde 10 hasta 49
vector = np.arange(10, 50)

print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
# Revertir el vector utilizando indexación inversa
reversed_vector = vector[::-1]

print("Vector original:", vector)
print("Vector revertido:", reversed_vector)

Vector original: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
Vector revertido: [49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [ ]:
# Definir los arrays A y B
A = np.random.randint(0, 2, 5)
B = np.random.randint(0, 8, 5)

print("Array A:", A)
print("Array B:", B)

# Verificar si los arrays A y B son iguales
son_iguales = np.array_equal(A, B)

if son_iguales:
    print("Los arrays A y B son iguales.")
else:
    print("Los arrays A y B no son iguales.")

Array A: [0 1 1 0 0]
Array B: [3 0 5 0 6]
Los arrays A y B no son iguales.


In [ ]:
# Crear una matriz 10x10 con valores enteros aleatorios entre 0 y 99
matriz = np.random.randint(0, 100, size=(10, 10))

# Encontrar el valor mínimo y máximo en la matriz
minimo_valor = np.min(matriz)
maximo_valor = np.max(matriz)

print("Matriz:")
print(matriz)
print("\nValor mínimo:", minimo_valor)
print("Valor máximo:", maximo_valor)

Matriz:
[[ 4 44 70 53 99 11 92 13 97 20]
 [96 90 70 41 91 61 88 51 80 60]
 [90 36 77 98 59 82 65 71 62 85]
 [72 41  1 77 35 72 25 66 20 74]
 [21 10 42 21 78 29 89 28 51 97]
 [59 51 12 57 92 99 99 38 14 88]
 [72 20 33 19 28 66 89 25 85 77]
 [15 62  8 18 74 77 70 18 96 86]
 [43 17 21 10 60 40 15 41 15 31]
 [79 12 65 79 10  7  6  1 41  6]]

Valor mínimo: 1
Valor máximo: 99


In [ ]:
# Crear una matriz tridimensional (3x3x3) con valores aleatorios
matriz_3d = np.random.rand(3, 3, 3)

print("Matriz tridimensional:")
print(matriz_3d)

Matriz tridimensional:
[[[0.42297665 0.7904825  0.31012632]
  [0.52578931 0.38653148 0.22948336]
  [0.79088689 0.17216821 0.62531621]]

 [[0.75479203 0.20464429 0.18858765]
  [0.10715792 0.49774897 0.24752884]
  [0.80637675 0.85353226 0.88098635]]

 [[0.84664021 0.42333076 0.9222355 ]
  [0.52094003 0.9655658  0.96045403]
  [0.4014978  0.34418695 0.74961917]]]


In [ ]:
# Definir el array arr
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Crear una copia del array para no modificar el original
arr_modificado = arr.copy()

# Reemplazar los números impares por -1
arr_modificado[arr_modificado % 2 != 0] = -1

print("Array original:", arr)
print("Array modificado con impares reemplazados por -1:", arr_modificado)

Array original: [1 2 3 4 5 6 7 8 9]
Array modificado con impares reemplazados por -1: [ 1 -1  3 -1  5 -1  7 -1  9]


In [ ]:
# Crear un array de tipo float
arr_float = np.array([1.0, 2.5, 3.7, 4.2])

print("Array de tipo float:")
print(arr_float)
print("Tipo de dato:", arr_float.dtype)

Array de tipo float:
[1.  2.5 3.7 4.2]
Tipo de dato: float64


In [ ]:
# Definir el array unidimensional
arr_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8])

# Convertir a un array bidimensional con 2 filas
arr_2d = arr_1d.reshape(2, -1)

print("Array unidimensional:")
print(arr_1d)
print("\nArray bidimensional con 2 filas:")
print(arr_2d)

Array unidimensional:
[1 2 3 4 5 6 7 8]

Array bidimensional con 2 filas:
[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
# Definir los arrays Z1 y Z2
Z1 = np.random.randint(0, 10, 10)
Z2 = np.random.randint(0, 10, 10)

print("Array Z1:", Z1)
print("Array Z2:", Z2)

# Encontrar los valores comunes entre Z1 y Z2
common_values = np.intersect1d(Z1, Z2)

print("Valores comunes entre Z1 y Z2:", common_values)

Array Z1: [0 2 7 0 6 2 7 3 7 6]
Array Z2: [6 4 4 8 3 2 9 9 3 7]
Valores comunes entre Z1 y Z2: [2 3 6 7]


In [ ]:
# Definir las matrices a y b
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

# Apilar verticalmente las matrices
c = np.vstack((a, b))

print(c)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
# Define the arrays a and b
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

# Stack the arrays horizontally
c = np.hstack((a, b))

print(c)

[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
# Crear el array tmp
tmp = np.arange(15)

# Obtener todos los elementos entre 5 y 10
result = tmp[(tmp >= 5) & (tmp <= 10)]

print(result)

[ 5  6  7  8  9 10]


In [ ]:
# Definir la función que maneja escalares
def pair_max(x, y):
    return max(x, y)

# Vectorizar la función para que funcione con arrays de NumPy
vectorized_pair_max = np.vectorize(pair_max)

# Definir los arrays a y b
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

# Aplicar la función vectorizada
result = vectorized_pair_max(a, b)

print(result)

[6 7 9 8 9 7 5]


In [2]:
import numpy as np
# Definir el arreglo arr
arr = np.arange(9).reshape(3, 3)
print("Arreglo original:")
print(arr)

# Intercambiar las columnas 1 y 2
arr[:, [1, 2]] = arr[:, [2, 1]]

# Imprimir el resultado
print("Arreglo con columnas 1 y 2 intercambiadas:")
print(arr)



Arreglo original:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
Arreglo con columnas 1 y 2 intercambiadas:
[[0 2 1]
 [3 5 4]
 [6 8 7]]


In [3]:
import numpy as np

# Crear un arreglo 2D de forma 5x3 con números decimales aleatorios entre 5 y 10
arr = np.random.uniform(5, 10, size=(5, 3))

# Imprimir el resultado
print("Arreglo 2D de forma 5x3 con números aleatorios entre 5 y 10:")
print(arr)

Arreglo 2D de forma 5x3 con números aleatorios entre 5 y 10:
[[8.94153336 9.47785123 8.13446949]
 [6.30818436 8.09333688 7.93995462]
 [7.76556306 9.59021335 7.8466458 ]
 [6.27754584 7.23074722 9.77524656]
 [8.47545745 5.27688775 8.85804655]]
